baseURL = 'https://jacknicol.com'
languageCode = 'en-us'
title = 'Jack Nicol'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "Hello, my name is Jack 👋 I’m a software engineer with a passion for distributed systems. Currently, you’ll find me as a Senior Engineer at Europe’s leading spend management solution, Pleo 💳. "
  author = 'Jack Nicol'

  [params.comments]
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'


[menu]
  [[menu.main]]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
